### ISSUE TITLE
2.2.5 用Pandas处理空缺值 df.loc 错误

### ISSUE THREAD

**Issue by getjake** [getjake/learn-quant-crypto#2]
```python
import pandas as pd
pd.set_option('expand_frame_repr', False)

df = pd.read_csv(
    filepath_or_buffer='/Users/jake/Documents/2020-刑不行-量化数字货币/2.Source/data/OKEX_BTC-USDT_20200302_1T.csv',
    skiprows=1,
    encoding='gbk'
)

# print(df)
# df[df['candle_begin_time'].isin(['2020-03-02 00:09:00+00:00', '2020-03-02 12:27:00+00:00'])]
index = df[df['candle_begin_time'].isin(['2020-03-02 00:09:00+00:00', '2020-03-02 12:27:00+00:00'])]

df.loc[index, '24小时'] = df['candle_begin_time']

```

错误代码
```
/usr/local/bin/python3.7 /Users/jake/Documents/2020-刑不行-量化数字货币/2.Source/program/myplayground/pandas_blank.py
Traceback (most recent call last):
  File "/Users/jake/Documents/2020-刑不行-量化数字货币/2.Source/program/myplayground/pandas_blank.py", line 14, in <module>
    df.loc[index, '24小时'] = df['candle_begin_time']
  File "/usr/local/lib/python3.7/site-packages/pandas/core/indexing.py", line 670, in __setitem__
    indexer = self._get_setitem_indexer(key)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/indexing.py", line 648, in _get_setitem_indexer
    return self._convert_tuple(key)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/indexing.py", line 733, in _convert_tuple
    idx = self._convert_to_indexer(k, axis=i)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/indexing.py", line 1732, in _convert_to_indexer
    return self._get_listlike_indexer(obj, axis, raise_missing=True)[1]
  File "/usr/local/lib/python3.7/site-packages/pandas/core/indexing.py", line 1553, in _get_listlike_indexer
    keyarr, indexer, o._get_axis_number(axis), raise_missing=raise_missing
  File "/usr/local/lib/python3.7/site-packages/pandas/core/indexing.py", line 1640, in _validate_read_indexer
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index([('c', 'a', 'n', 'd', 'l', 'e', '_', 'b', 'e', 'g', 'i', 'n', '_', 't', 'i', 'm', 'e'),\n                                                                        ('o', 'p', 'e', 'n'),\n                                                                        ('h', 'i', 'g', 'h'),\n                                                                             ('l', 'o', 'w'),\n                                                                   ('c', 'l', 'o', 's', 'e'),\n                                                              ('v', 'o', 'l', 'u', 'm', 'e')],\n      dtype='object')] are in the [index]"

Process finished with exit code 1
```

**Comment by getjake** [comment]
问题解决了
```python
index = df[df['candle_begin_time'].isin(['2020-03-02 00:09:00+00:00', '2020-03-02 12:27:00+00:00'])].index
```
